x-runtipi:
  schema_version: 2

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    x-runtipi:
      is_main: true
      internal_port: 9696
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ}
      PROWLARR__AUTH__APIKEY: ${PROWLARR_API_KEY}
      PROWLARR__AUTH__METHOD: External
    volumes:
      - ${APP_DATA_DIR}/data:/config
    restart: unless-stopped
